[package]
name = "hitster"
version = "0.1.0"
edition = "2024"

[lib]
name = "hitster"
path = "src/lib.rs"

[dependencies]
rspotify = { version = "0.13", features = ["client-reqwest", "reqwest-native-tls"] }
tokio = { version = "1.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
clap = { version = "4.0", features = ["derive"] }
anyhow = "1.0"
thiserror = "1.0"
dotenv = "0.15"
futures = "0.3"
oxidize-pdf = "0.1"

[dev-dependencies]
