name: Build and Push Docker Image

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - uses: actions/checkout@v5
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Setup cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Build Docker Image
        env:
          SQLX_OFFLINE: true
        run: nix build .#dockerImage

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Load and Push Docker Image
        run: |
          docker load < result
          IMAGE_ID=$(docker images | grep '^hitster' | awk '{print $3}')
          docker tag $IMAGE_ID ghcr.io/${{ github.repository }}:latest
          docker tag $IMAGE_ID ghcr.io/${{ github.repository }}:${{ github.sha }}
          docker push ghcr.io/${{ github.repository }}:latest
          docker push ghcr.io/${{ github.repository }}:${{ github.sha }}
