name: PR CI

on:
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  id-token: write

jobs:
  hygiene:
    name: Format and Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Setup cache
        uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Check formatting
        env:
          SQLX_OFFLINE: true
        run: nix develop --command cargo fmt -- --check
      - name: Run clippy
        env:
          SQLX_OFFLINE: true
        run: nix develop --command cargo clippy -- -D warnings

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Setup cache
        uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Run tests
        env:
          SQLX_OFFLINE: true
        run: nix develop --command cargo test --verbose